name: NC Auto deploy from gitHub
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy_source:
    name: NordGO!5
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#Python Procedule
      - name: Install Python
        uses: actions/setup-python@v3
      - name: Install Py Dependencies
        run:  |
          python -m pip install --upgrade pip setuptools wheel
          pip install build
       # - name: Python Build! (working on it)
       # run: python -m build
#Node.js Procedule | Can exist with python run or be exchanged
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
#Zip Compile | Can be removed, it only compress the file directory defined on line 40 into a location
      - name: zip
        uses: montudor/action-zip@v0.1.0 #https://github.com/montudor/action-zip/blob/master/README.md
        with:
          args: zip -qq -r ./bundle.zip ./ #Directory can be changed here
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }} #Access key stored on GitHub Vault
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #Access key stored on GitHub Vault
          aws_region: us-east-1 #Change tu EU central on final build
          function_name: nord-test-func4 #Could be a variable i think, but why?
          zip_file: bundle.zip